bot:
  token: ODk1ODEyMDk2NDU2MDExNzg2.YV-ABw.N3JAvRe0ZlmYL-KTLCGTXRuCnvE
  owner_ids:
    - 455221909257453577
  prefix: ^
  default_bet: 125
  bonus_multiplier: 20 # bonus = default_bet * multiplier
  bonus_cooldown: 2 # Bonus every x hours
